### PR TITLE
Rely on proper libzim version 9.1.0

### PR DESCRIPTION
**Pull request by kelson42**
Substainable implementation of #175 (Use stable libzim release)

### CODE REVIEW

**Review by rgaudin — APPROVED** [review]
👍

**Comment by rgaudin** [comment]
FYI the PR was not OK ; it didn't change the libzim version used for release ; fixing that on main before releasing

**Comment by kelson42** [comment]
@rgaudin OK. Current system is error prone. Libzim version should be defined only in one place and ideally not as an env. variable.

**Comment by rgaudin** [comment]
I agree. We actually have it in code and the env is here to allow changing it easily. Maybe we should remove them from the workflows.

**Pull request merged**
