### PR TITLE
Reorganize wrapper and add search and suggestion

### PR DESCRIPTION
**Pull request by mgautierfr**
New update of python-libzim.

This PR is pretty big.
- It rewrite a part of the wrapper to have a better organization for our wrapper.
- Add search and suggestion wrapping (in two different submodule)

Better to review commit by commit as the whole change is pretty complex.

Unit tests have been update with last version of the testing zim files.

### CODE REVIEW

**Comment by mgautierfr** [comment]
The failing unit test is fixed in https://github.com/openzim/libzim/pull/625

**Comment by rgaudin** [comment]
> The failing unit test is fixed in [openzim/libzim#625](https://github.com/openzim/libzim/pull/625)

Great! Once this is merged we'll update the nightly we build against

**Comment by kelson42** [comment]
@rgaudin @mgautierfr What is the review process/status.

**Comment by rgaudin** [comment]
@mgautierfr, tests are now passing

**Comment by rgaudin** [comment]
@mgautierfr I also squeezed-in a tiny commit to set the charset on add_metadata's default mimetype. We can add that separately but since it's harmless…

**Review by rgaudin — APPROVED** [review]
It's a very large PR indeed with both code moved and a lot of new code introduced.

Really appreciate the verbose helpers on the tricky part of the Cython module.

I've directly edited many docstrings to fix some typos, complete some and harmonize.

Please take a quick look at b0fada3 where I change the loader.

**Pull request merged**
