### PR TITLE
Camel Case to Snake Case

### PR DESCRIPTION
**Pull request by SrisharanVS**
All Camel Case variables have been converted to Snake Case. Pascal Case still exists.. I think another PR can be opened to fix it..

### CODE REVIEW

**Review by benoit74 — CHANGES_REQUESTED** [review]
@SrisharanVS this PR has obviously been generated with an AI tool, at least there are many space / carriage returns changes which are probably not wanted. Using automated tools is strongly advised to use with great care. Please fix any unrelated changes introduced in this PR or we will have to close this. Please also explain how you tested these changes, just triggerring the changes with an automated tool and not testing anything does not help us at all to make any progress.

**Comment by SrisharanVS** [comment]
> @SrisharanVS this PR has obviously been generated with an AI tool, at least there are many space / carriage returns changes which are probably not wanted. Using automated tools is strongly advised to use with great care. Please fix any unrelated changes introduced in this PR or we will have to close this. Please also explain how you tested these changes, just triggerring the changes with an automated tool and not testing anything does not help us at all to make any progress.

I'm sorry, this was my first time contributing to openzim, I have not tested it, but I can assure you that I have not used any AI tools.I will fix any unrelated changes introduced in this PR.

**Comment by SrisharanVS** [comment]
I think it would be better to close this and I will open another PR.?

**Comment by rgaudin** [comment]
@SrisharanVS when you do, please keep in mind that this issue is about the python API only. Zero change to the C++ code or API is expected

**Comment by benoit74** [comment]
> I'm sorry, this was my first time contributing to openzim, I have not tested it, but I can assure you that I have not used any AI tools.I will fix any unrelated changes introduced in this PR.

Sorry if it wasn't generated with AI then, but we get too many of these automated things in PRs which do not help us at all. It is usually very quick to generated for the contributor, but we have more work left than work done in such a case. Testing is part of the development and should not be left for the reviewer (which is only supposed to ... review ...). We do not have dedicated testers at openZIM.

Thank you for considering contributing then!

**Pull request closed without merging**
